#!/bin/bash

# Check number of arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: ./onescp <local_file> <target_server> <target_path>"
    exit 1
fi

LOCAL_FILE=$1
TARGET_SERVER=$2
TARGET_PATH=$3

scp -r "$LOCAL_FILE" "$TARGET_SERVER":"$TARGET_PATH"

if [ $? -eq 0 ]; then
    echo "File copied successfully."
else
    echo "File copy failed."
fi
